import React from "react";
import "./globals.css";
import type { Metadata } from "next";

import Navigation from "./components/navigation";
import { space } from "./fonts/spaceGrotesk";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>😎 Next Js 13</title>
      </head>
      <body className={space.className}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
